# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: demo/v1.proto for package 'demo.v1'
# Original file comments:
# Generated by Microsoft TypeSpec
#
# DemoService — Echo + Health
# Simple RPC service used to demonstrate the full TypeSpec → proto → gRPC pipeline.

require 'grpc'
require 'demo/v1_pb'

module Demo
  module V1
    module DemoService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'demo.v1.DemoService'

        # Echo a message back to the caller.
        rpc :Echo, ::Demo::V1::EchoRequest, ::Demo::V1::EchoResponse
        # Return the current health status of this service.
        rpc :Health, ::Google::Protobuf::Empty, ::Demo::V1::HealthResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
