# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo/v1.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'demo/v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdemo/v1.proto\x12\x07\x64\x65mo.v1\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\x0b\x45\x63hoRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"(\n\x0c\x45\x63hoResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"\x0f\n\rHealthRequest\"(\n\x0eHealthResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status2}\n\x0b\x44\x65moService\x12\x33\n\x04\x45\x63ho\x12\x14.demo.v1.EchoRequest\x1a\x15.demo.v1.EchoResponse\x12\x39\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x17.demo.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=55
  _globals['_ECHOREQUEST']._serialized_end=94
  _globals['_ECHORESPONSE']._serialized_start=96
  _globals['_ECHORESPONSE']._serialized_end=136
  _globals['_HEALTHREQUEST']._serialized_start=138
  _globals['_HEALTHREQUEST']._serialized_end=153
  _globals['_HEALTHRESPONSE']._serialized_start=155
  _globals['_HEALTHRESPONSE']._serialized_end=195
  _globals['_DEMOSERVICE']._serialized_start=197
  _globals['_DEMOSERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
