//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: demo/v1.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Demo_V1_DemoServiceClient`, then call methods of this protocol to make API calls.
internal protocol Demo_V1_DemoServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? { get }

  func echo(
    _ request: Demo_V1_EchoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Demo_V1_EchoRequest, Demo_V1_EchoResponse>

  func health(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Demo_V1_HealthResponse>
}

extension Demo_V1_DemoServiceClientProtocol {
  internal var serviceName: String {
    return "demo.v1.DemoService"
  }

  /// Echo a message back to the caller.
  ///
  /// - Parameters:
  ///   - request: Request to send to Echo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func echo(
    _ request: Demo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Demo_V1_EchoRequest, Demo_V1_EchoResponse> {
    return self.makeUnaryCall(
      path: Demo_V1_DemoServiceClientMetadata.Methods.echo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  /// Return the current health status of this service.
  ///
  /// - Parameters:
  ///   - request: Request to send to Health.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func health(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Demo_V1_HealthResponse> {
    return self.makeUnaryCall(
      path: Demo_V1_DemoServiceClientMetadata.Methods.health.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeHealthInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Demo_V1_DemoServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Demo_V1_DemoServiceNIOClient")
internal final class Demo_V1_DemoServiceClient: Demo_V1_DemoServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the demo.v1.DemoService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Demo_V1_DemoServiceNIOClient: Demo_V1_DemoServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the demo.v1.DemoService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Demo_V1_DemoServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? { get }

  func makeEchoCall(
    _ request: Demo_V1_EchoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Demo_V1_EchoRequest, Demo_V1_EchoResponse>

  func makeHealthCall(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Demo_V1_HealthResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Demo_V1_DemoServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Demo_V1_DemoServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeEchoCall(
    _ request: Demo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Demo_V1_EchoRequest, Demo_V1_EchoResponse> {
    return self.makeAsyncUnaryCall(
      path: Demo_V1_DemoServiceClientMetadata.Methods.echo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  internal func makeHealthCall(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Demo_V1_HealthResponse> {
    return self.makeAsyncUnaryCall(
      path: Demo_V1_DemoServiceClientMetadata.Methods.health.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeHealthInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Demo_V1_DemoServiceAsyncClientProtocol {
  internal func echo(
    _ request: Demo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Demo_V1_EchoResponse {
    return try await self.performAsyncUnaryCall(
      path: Demo_V1_DemoServiceClientMetadata.Methods.echo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  internal func health(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) async throws -> Demo_V1_HealthResponse {
    return try await self.performAsyncUnaryCall(
      path: Demo_V1_DemoServiceClientMetadata.Methods.health.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeHealthInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Demo_V1_DemoServiceAsyncClient: Demo_V1_DemoServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Demo_V1_DemoServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Demo_V1_DemoServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'echo'.
  func makeEchoInterceptors() -> [ClientInterceptor<Demo_V1_EchoRequest, Demo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when invoking 'health'.
  func makeHealthInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Demo_V1_HealthResponse>]
}

internal enum Demo_V1_DemoServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "DemoService",
    fullName: "demo.v1.DemoService",
    methods: [
      Demo_V1_DemoServiceClientMetadata.Methods.echo,
      Demo_V1_DemoServiceClientMetadata.Methods.health,
    ]
  )

  internal enum Methods {
    internal static let echo = GRPCMethodDescriptor(
      name: "Echo",
      path: "/demo.v1.DemoService/Echo",
      type: GRPCCallType.unary
    )

    internal static let health = GRPCMethodDescriptor(
      name: "Health",
      path: "/demo.v1.DemoService/Health",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Demo_V1_DemoServiceProvider: CallHandlerProvider {
  var interceptors: Demo_V1_DemoServiceServerInterceptorFactoryProtocol? { get }

  /// Echo a message back to the caller.
  func echo(request: Demo_V1_EchoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Demo_V1_EchoResponse>

  /// Return the current health status of this service.
  func health(request: SwiftProtobuf.Google_Protobuf_Empty, context: StatusOnlyCallContext) -> EventLoopFuture<Demo_V1_HealthResponse>
}

extension Demo_V1_DemoServiceProvider {
  internal var serviceName: Substring {
    return Demo_V1_DemoServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Echo":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Demo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Demo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeEchoInterceptors() ?? [],
        userFunction: self.echo(request:context:)
      )

    case "Health":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Demo_V1_HealthResponse>(),
        interceptors: self.interceptors?.makeHealthInterceptors() ?? [],
        userFunction: self.health(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Demo_V1_DemoServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Demo_V1_DemoServiceServerInterceptorFactoryProtocol? { get }

  /// Echo a message back to the caller.
  func echo(
    request: Demo_V1_EchoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Demo_V1_EchoResponse

  /// Return the current health status of this service.
  func health(
    request: SwiftProtobuf.Google_Protobuf_Empty,
    context: GRPCAsyncServerCallContext
  ) async throws -> Demo_V1_HealthResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Demo_V1_DemoServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Demo_V1_DemoServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Demo_V1_DemoServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Demo_V1_DemoServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Echo":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Demo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Demo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeEchoInterceptors() ?? [],
        wrapping: { try await self.echo(request: $0, context: $1) }
      )

    case "Health":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Demo_V1_HealthResponse>(),
        interceptors: self.interceptors?.makeHealthInterceptors() ?? [],
        wrapping: { try await self.health(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Demo_V1_DemoServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'echo'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEchoInterceptors() -> [ServerInterceptor<Demo_V1_EchoRequest, Demo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when handling 'health'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeHealthInterceptors() -> [ServerInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Demo_V1_HealthResponse>]
}

internal enum Demo_V1_DemoServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "DemoService",
    fullName: "demo.v1.DemoService",
    methods: [
      Demo_V1_DemoServiceServerMetadata.Methods.echo,
      Demo_V1_DemoServiceServerMetadata.Methods.health,
    ]
  )

  internal enum Methods {
    internal static let echo = GRPCMethodDescriptor(
      name: "Echo",
      path: "/demo.v1.DemoService/Echo",
      type: GRPCCallType.unary
    )

    internal static let health = GRPCMethodDescriptor(
      name: "Health",
      path: "/demo.v1.DemoService/Health",
      type: GRPCCallType.unary
    )
  }
}
